import type { Category, FieldTemplate, ProjectLane, Task, ViewPreset, WeekDay, Widget } from './types';

export const appDate = {
  today: '2026-06-08',
  weekLabel: '第 24 周',
};

export const categories: Category[] = [
  { id: 'writing', name: '论文', color: '#5b6ee1', soft: '#e8ebff' },
  { id: 'experiment', name: '实验', color: '#d4554f', soft: '#ffe9e6' },
  { id: 'data', name: '数据', color: '#2f8b83', soft: '#dff5f1' },
  { id: 'learning', name: '学习', color: '#b7791f', soft: '#fff1d8' },
  { id: 'life', name: '生活', color: '#7a5c98', soft: '#f1e8fb' },
  { id: 'recovery', name: '恢复', color: '#4f7b62', soft: '#e4f2e8' },
];

export const projects: ProjectLane[] = [
  {
    id: 'p-paper-ta',
    name: 'TA 论文',
    category: 'writing',
    stage: '引言第二版和图 3 逻辑收束',
    status: 'active',
    deadline: '2026-07-18',
    progress: 62,
    next: '锁定图 3 数据和引言逻辑',
    blocker: '等复测数据确认后才能收束结果段落',
    cadence: '每日 2 个深度写作块',
    milestones: [
      { id: 'm-ta-intro', title: '引言第二版', date: '2026-06-10', done: false },
      { id: 'm-ta-fig3', title: '图 3 数据定稿', date: '2026-06-14', done: false },
      { id: 'm-ta-draft', title: '全文 v0.8', date: '2026-06-28', done: false },
    ],
    trend: [36, 44, 52, 58, 62],
  },
  {
    id: 'p-substrate-exp',
    name: '底物谱实验',
    category: 'experiment',
    stage: '异常点复测',
    status: 'risk',
    deadline: '2026-06-24',
    progress: 44,
    next: '完成 HPLC 复测并确认条件表',
    blocker: '仪器预约窗口紧张',
    cadence: '隔日实验批次',
    milestones: [
      { id: 'm-substrate-hplc', title: '异常样品复测', date: '2026-06-09', done: false },
      { id: 'm-substrate-table', title: '下一轮条件表', date: '2026-06-12', done: false },
      { id: 'm-substrate-batch', title: '正式批次启动', date: '2026-06-17', done: false },
    ],
    trend: [18, 27, 33, 41, 44],
  },
  {
    id: 'p-ml-learning',
    name: '新技术学习',
    category: 'learning',
    stage: '可复现实例',
    status: 'active',
    deadline: '2026-07-05',
    progress: 28,
    next: '完成小型 notebook',
    blocker: '避免和论文高脑力时段叠加',
    cadence: '每周 2 次 80 分钟',
    milestones: [
      { id: 'm-ml-env', title: '环境与示例跑通', date: '2026-06-10', done: false },
      { id: 'm-ml-notebook', title: '小型 notebook', date: '2026-06-19', done: false },
      { id: 'm-ml-summary', title: '方法笔记整理', date: '2026-06-30', done: false },
    ],
    trend: [8, 15, 20, 24, 28],
  },
  {
    id: 'p-life-rhythm',
    name: '生活维护',
    category: 'life',
    stage: '晚间恢复边界',
    status: 'active',
    deadline: '2026-06-30',
    progress: 71,
    next: '固定晚间恢复和伴侣沟通时间',
    blocker: '深夜临时补写作会挤压恢复',
    cadence: '每日轻量维护',
    milestones: [
      { id: 'm-life-evening', title: '固定晚间恢复', date: '2026-06-11', done: false },
      { id: 'm-life-review', title: '周复盘节奏', date: '2026-06-14', done: false },
      { id: 'm-life-boundary', title: '深夜边界复查', date: '2026-06-21', done: false },
    ],
    trend: [48, 55, 63, 68, 71],
  },
];

export const tasks: Task[] = [
  {
    id: 't1',
    title: '转氨酶论文引言重写',
    category: 'writing',
    projectId: 'p-paper-ta',
    date: '2026-06-08',
    start: '08:40',
    duration: 110,
    energy: '高',
    location: '',
    status: 'active',
    priority: 1,
    standard: '完成引言第二版并标出缺口句',
    dependency: '',
    detail: '围绕胺供体优化、平衡推动和工艺适配重新组织段落。',
    paperFields: {
      chapter: '引言',
      figure: '图 3 逻辑铺垫',
      version: 'v0.7.2',
      feedback: '导师批注 4 条',
    },
  },
  {
    id: 't2',
    title: 'HPLC 样品复测',
    category: 'experiment',
    projectId: 'p-substrate-exp',
    date: '2026-06-08',
    start: '10:50',
    duration: 75,
    energy: '中',
    location: '分析室',
    status: 'planned',
    priority: 2,
    standard: '完成 6 个异常峰样品复测',
    dependency: '仪器预约 10:30 可用',
    detail: '记录柱温、流动相批号和样品放置时间。',
    experimentFields: {
      sample: '6 个异常峰样品',
      instrument: 'HPLC',
      condition: '柱温和流动相批号固定',
      waiting: '等待 LC 导出结果',
      reservation: '10:30 已预约',
    },
  },
  {
    id: 't3',
    title: '图 3 数据清洗',
    category: 'data',
    projectId: 'p-paper-ta',
    date: '2026-06-08',
    start: '14:00',
    duration: 95,
    energy: '高',
    location: '',
    status: 'planned',
    priority: 3,
    standard: '输出可复现脚本和新版图表草稿',
    dependency: '等待复测数据导出',
    detail: '统一重复实验命名，检查空白扣除和归一化逻辑。',
    dataFields: {
      source: 'HPLC 复测导出表',
      notebook: 'fig3-cleaning.ipynb',
      output: '新版图表草稿和清洗脚本',
      reproducibility: '脚本可从原始导出表重跑',
    },
  },
  {
    id: 't4',
    title: '晚间散步和家务整理',
    category: 'life',
    projectId: 'p-life-rhythm',
    date: '2026-06-08',
    start: '20:10',
    duration: 55,
    energy: '低',
    location: '家',
    status: 'planned',
    standard: '完成厨房整理并留出无屏幕休息',
    dependency: '',
    detail: '生活约束作为正式日程，不挤压到深夜写作。',
    lifeFields: {
      place: '家',
      people: '自己 / 伴侣',
      boundary: '21:30 后不补写作',
      recoveryLevel: '低负荷恢复',
    },
  },
  {
    id: 't5',
    title: '实验方案下一轮条件表',
    category: 'experiment',
    projectId: 'p-substrate-exp',
    date: '2026-06-09',
    start: '09:20',
    duration: 100,
    energy: '高',
    location: '实验室',
    status: 'blocked',
    standard: '确认 pH、温度、胺供体浓度三因素组合',
    dependency: '等待上轮 LC 结果',
    delayReason: '关键复测结果未回收',
    detail: '先列候选矩阵，等数据后锁定正式批次。',
    experimentFields: {
      sample: '底物谱下一轮样品',
      instrument: '移液器 / 恒温振荡器',
      condition: 'pH、温度、胺供体浓度',
      waiting: '等待上轮 LC 结果',
      reservation: '未锁定',
    },
  },
  {
    id: 't6',
    title: '机器学习建模教程',
    category: 'learning',
    projectId: 'p-ml-learning',
    date: '2026-06-10',
    start: '15:00',
    duration: 80,
    energy: '中',
    location: '',
    status: 'planned',
    standard: '复现一个小型回归 notebook',
    dependency: '',
    detail: '只保留和实验数据分析相关的部分。',
  },
  {
    id: 't7',
    title: '共同作者反馈整合',
    category: 'writing',
    projectId: 'p-paper-ta',
    date: '2026-06-11',
    start: '09:00',
    duration: 130,
    energy: '高',
    location: '办公室',
    status: 'delayed',
    standard: '回复 12 条批注并更新版本号',
    dependency: '导师批注',
    delayReason: '实验数据确认推迟',
    detail: '将语言问题和科学解释问题拆开处理。',
    paperFields: {
      chapter: '结果与讨论',
      figure: '图 3 / 图 4',
      version: 'v0.7.2 comments',
      feedback: '共同作者 12 条批注',
    },
  },
  {
    id: 't8',
    title: '周复盘和下周排程',
    category: 'recovery',
    projectId: 'p-life-rhythm',
    date: '2026-06-14',
    start: '16:30',
    duration: 70,
    energy: '低',
    location: '家',
    status: 'planned',
    standard: '确定下周 3 个推进点和 2 个保护时段',
    dependency: '本周任务状态更新',
    detail: '复盘延期原因、脑力负荷和生活时间是否被侵占。',
    lifeFields: {
      place: '家',
      people: '自己',
      boundary: '下周至少保留 2 个晚间恢复时段',
      recoveryLevel: '周复盘',
    },
  },
];

export const weekDays: WeekDay[] = [
  { date: '2026-06-08', label: '周一', short: '6/8' },
  { date: '2026-06-09', label: '周二', short: '6/9' },
  { date: '2026-06-10', label: '周三', short: '6/10' },
  { date: '2026-06-11', label: '周四', short: '6/11' },
  { date: '2026-06-12', label: '周五', short: '6/12' },
  { date: '2026-06-13', label: '周六', short: '6/13' },
  { date: '2026-06-14', label: '周日', short: '6/14' },
];

export const widgets: Widget[] = [
  { id: 'timeline', name: '今日时间轴', visible: true },
  { id: 'project-progress', name: '课题/项目推进', visible: true },
  { id: 'deadline-alerts', name: '检查点提醒', visible: true },
  { id: 'energy-load', name: '精力负荷', visible: true },
  { id: 'life-rhythm', name: '家庭生活', visible: true },
  { id: 'inbox', name: '收件箱', visible: false },
];

export const viewPresets: ViewPreset[] = [
  { id: 'today-execution', name: '今日执行', widgetIds: ['timeline', 'project-progress', 'deadline-alerts'], focusCategories: ['writing', 'experiment', 'data'] },
  { id: 'paper-sprint', name: '论文冲刺', widgetIds: ['timeline', 'project-progress', 'energy-load'], focusCategories: ['writing', 'data'] },
  { id: 'experiment-cycle', name: '实验周期', widgetIds: ['timeline', 'deadline-alerts', 'energy-load'], focusCategories: ['experiment', 'data'] },
  { id: 'weekly-review', name: '周复盘', widgetIds: ['project-progress', 'energy-load', 'life-rhythm'], focusCategories: ['writing', 'experiment', 'life', 'recovery'] },
  { id: 'life-balance', name: '生活平衡', widgetIds: ['life-rhythm', 'energy-load', 'timeline'], focusCategories: ['life', 'recovery'] },
];

export const fieldTemplates: FieldTemplate[] = [
  { id: 'writing', name: '论文任务', fields: ['章节', '图表', '版本', '共同作者反馈', '做到什么算完成'] },
  { id: 'experiment', name: '实验任务', fields: ['样品', '仪器', '条件', '等待结果/等待事项', '预约状态'] },
  { id: 'data', name: '数据任务', fields: ['数据来源', '脚本/Notebook', '输出物', '复现状态'] },
  { id: 'life', name: '生活/恢复', fields: ['地点', '对象', '边界说明', '恢复等级'] },
];
